<?php
$app_strings['Received Shipment'] = 'Received Shipment';
$app_strings['Completed'] = 'Completed';
$app_strings['Accepted'] = 'Accepted';
$app_strings['LBL_CLOSE_WON'] = 'Closed Won';
$app_strings['LBL_CLOSE_LOST'] = 'Closed Lost';
$app_strings['Closed Won'] = 'Closed Won';
$app_strings['Approved'] = 'Approved';
$app_strings['WAREHOUSED'] = 'WAREHOUSED';
$app_strings['NOTWAREHOUSED'] = 'Not WAREHOUSED';
$app_strings['DELIVERYED'] = 'DELIVERYED';
$app_strings['CHECKIN'] = 'CHECKIN';
$app_strings['CHECKEND'] = 'CHECKEND';
$app_strings['LBL_GATHERED'] = 'GATHERED';
$app_strings['Rejected'] = 'Rejected';
$app_strings['approving'] = 'approving';
$app_strings['unapproved'] = 'Rejected';
$app_strings['Approve'] = 'Approve';
$app_strings['CONSTANTS_SO_CREATED'] = 'CREATED';
$app_strings['CONSTANTS_SO_CANCELED'] = 'CANCELED';
$app_strings['CONSTANTS_RETURNED'] = 'RETURNED';
$app_strings['CONSTANTS_DELIVERYED'] = 'DELIVERYED';
$app_strings['CONSTANTS_NOTDELIVERYED'] = 'Not DELIVERYED';
$app_strings['CONSTANTS_SO_FINISHED'] = 'FINISHED';
$app_strings['CONSTANTS_SO_NOTFINISHED'] = 'NOTFINISHED';
$app_strings['CONSTANTS_EQUAL'] = 1;
$app_strings['CONSTANTS_MORETHAN'] = 2;
$app_strings['CONSTANTS_LESSTHAN'] = -1;
$app_strings['CONSTANTS_MONEY_CREATED'] = 'Created';
$app_strings['CONSTANTS_MONEY_SEMICREATED'] = 'Semi Created';
$app_strings['CONSTANTS_MONEY_NOTCREATED'] = 'Not Created';
$app_strings['CONSTANTS_CHARGED'] = 'Charged';
$app_strings['CONSTANTS_UNCHARGED'] = 'Not Charged';
$app_strings['CONSTANTS_GATHERED'] = 'Collectioned';
$app_strings['CONSTANTS_UNGATHER'] = 'Not Collectioned';
$app_strings['CONSTANTS_EXPENSED'] = 'Expensed';
$app_strings['CONSTANTS_EXPENSING'] = 'Expensing';
$app_strings['CONSTANTS_APPOK'] = 1;//approve success
$app_strings['CONSTANTS_APPIN'] = 2;//approve in process
$app_strings['CONSTANTS_APPNOTOK'] = -1;//approve failed
$app_strings['CONSTANTS_CANCELED'] = -2;//approve canceled
?>