<?php
$app_strings['Received Shipment'] = '货已到';
$app_strings['Completed'] = '已完成';
$app_strings['Accepted'] = '已接受';
$app_strings['LBL_CLOSE_WON'] = '谈成结束';
$app_strings['LBL_CLOSE_LOST'] = '未成结束';
$app_strings['Closed Won'] = '谈成结束';
$app_strings['Approved'] = '已批准';
$app_strings['WAREHOUSED'] = '已入库';
$app_strings['NOTWAREHOUSED'] = '未入库';
$app_strings['DELIVERYED'] = '已出库';
$app_strings['CHECKIN'] = '盘存入库';
$app_strings['CHECKEND'] = '盘点结束';
$app_strings['LBL_GATHERED'] = '已收';
$app_strings['Rejected'] = '已拒绝';
$app_strings['approving'] = '待批准';
$app_strings['unapproved'] = '已拒绝';
$app_strings['Approve'] = '审批';
$app_strings['CONSTANTS_SO_CREATED'] = '已创建';
$app_strings['CONSTANTS_SO_CANCELED'] = '已撤单';
$app_strings['CONSTANTS_RETURNED'] = '已驳回';
$app_strings['CONSTANTS_DELIVERYED'] = '已出库';
$app_strings['CONSTANTS_NOTDELIVERYED'] = '未出库';
$app_strings['CONSTANTS_SO_FINISHED'] = '履行完毕';
$app_strings['CONSTANTS_SO_NOTFINISHED'] = '部分履行';
$app_strings['CONSTANTS_EXPENSED'] = '已报销';
$app_strings['CONSTANTS_EXPENSING'] = '待批';
$app_strings['CONSTANTS_GATHERED'] = '已收';
$app_strings['CONSTANTS_UNGATHER'] = '未收';
$app_strings['CONSTANTS_CHARGED'] = '已付';
$app_strings['CONSTANTS_UNCHARGED'] = '未付';
$app_strings['CONSTANTS_EQUAL'] = 1;
$app_strings['CONSTANTS_MORETHAN'] = 2;
$app_strings['CONSTANTS_LESSTHAN'] = -1;
$app_strings['CONSTANTS_MONEY_CREATED'] = '已创建';
$app_strings['CONSTANTS_MONEY_SEMICREATED'] = '部分创建';
$app_strings['CONSTANTS_MONEY_NOTCREATED'] = '未创建';
$app_strings['CONSTANTS_APPOK'] = 1;//approve success
$app_strings['CONSTANTS_APPIN'] = 2;//approve in process
$app_strings['CONSTANTS_APPNOTOK'] = -1;//approve failed
$app_strings['CONSTANTS_CANCELED'] = -2;//approve canceled
?>