/*********************************************************************************

** The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ********************************************************************************/

	
	var alert_arr = {       DELETE:'Are you sure you want to delete the selected ',
							RECORDS:' records?',
							SELECT:'Please select at least one entity',
							DELETE_ACCOUNT:'Deleting this account(s) will remove its related Potentials & Quotes. Are you sure you want to delete the selected ',
							DELETE_VENDOR:'Deleting this vendor(s) will remove its related Purchase Orders. Are you sure you want to delete the selected ',
							SELECT_MAILID:'Please Select a mailid',
							OVERWRITE_EXISTING_ACCOUNT2:') address details?',
							MISSING_FIELDS:'Missing required fields:',
							NOT_ALLOWED_TO_EDIT:'you are not allowed to edit this field',
							COLUMNS_CANNOT_BE_EMPTY:'Selected Columns cannot be empty',
							CANNOT_BE_EMPTY:' cannot be empty',
							CANNOT_BE_NONE:' cannot be none',
							ENTER_VALID:'Please enter a valid ',
							SHOULDBE_LESS:' should be less than ',
							SHOULDBE_LESS_EQUAL:' should be less than or equal to ',
							SHOULDBE_EQUAL:' should be equal to ',
							SHOULDBE_GREATER:' should be greater than ',
							SHOULDBE_GREATER_EQUAL:' should be greater than or equal to ',
							INVALID:'Invalid ',
							EXCEEDS_MAX:' exceeds the maximum limit ',
							OUT_OF_RANGE:' is out of range',
							SHOULDNOTBE_EQUAL:' should not be equal to ',
							PORTAL_PROVIDE_EMAILID:'Portal user should provide email Id for portal login',
							ADD_CONFIRMATION:'Are you sure you want to add the selected ',
							ACCOUNTNAME_CANNOT_EMPTY:'AccountName Cannot be Empty',
							CANT_SELECT_CONTACTS:"You can\'t select related contacts from Lead",
							LBL_THIS:'This ',
							DOESNOT_HAVE_MAILIDS:" doesn\'t have any mail ids",
							ARE_YOU_SURE:'Are you sure?',
							DOESNOT_HAVE_AN_MAILID:'" '+"doesn\'t have an Email Id",
							MISSING_REQUIRED_FIELDS:'Missing required fields: ',
							READONLY:"it\'s readonly",
							SELECT_ATLEAST_ONE_USER:'Please select at least one user',
							DISABLE_SHARING_CONFIRMATION:'Are you sure you want to disable sharing for selected ',
							USERS:' user(s) ?',
							ENDTIME_GREATER_THAN_STARTTIME:'End Time should be greater than Start Time ',
							FOLLOWUPTIME_GREATER_THAN_STARTTIME:'Followup Time should be greater than End Time ',
							MISSING_EVENT_NAME:'Missing Event Name',
							EVENT_TYPE_NOT_SELECTED:'Event Type is not selected',
							CLOSEDATE_CANNOT_BE_EMPTY:'Close Date field cannot be empty',
							SITEURL_CANNOT_BE_EMPTY:'Site Url cannot be empty',
							SITENAME_CANNOT_BE_EMPTY:'Site Name cannot be empty',
							LISTPRICE_CANNOT_BE_EMPTY:'List Price cannot be empty',
							INVALID_LIST_PRICE:'Invalid List Price',
							PROBLEM_ACCESSSING_URL:'Problem accessing url: ',
							CODE:' Code: ',
							WISH_TO_QUALIFY_MAIL_AS_CONTACT:'Are you sure you wish to Qualify this Mail as Contact?',
							SELECT_ATLEAST_ONEMSG_TO_DEL:'Please select at least one message to delete',
							ERROR:'Error',
							FIELD_TYPE_NOT_SELECTED:'Field Type is not selected',
							SPECIAL_CHARACTERS_NOT_ALLOWED:'Special characters are not allowed in Label field',
							PICKLIST_CANNOT_BE_EMPTY:'Picklist value cannot be empty',
							DUPLICATE_VALUES_FOUND:'Duplicate Values found',
							DUPLICATE_MAPPING_ACCOUNTS:'Duplicate mapping for accounts!!',
							DUPLICATE_MAPPING_CONTACTS:'Duplicate mapping for Contacts!!',
							DUPLICATE_MAPPING_POTENTIAL:'Duplicate mapping for Potential!!',
							ERROR_WHILE_EDITING:'Error while Editing',
							CURRENCY_CHANGE_INFO:'Currency Changes has been made Successfully',
							CURRENCY_CONVERSION_INFO:'Are you using Dollar $ as Currency? \n Click OK to remain as $, Cancel to change the currency conversion rate.',
							THE_EMAILID: "The email id \'",
							EMAIL_FIELD_INVALID:"\' in the email field is invalid",
							MISSING_REPORT_NAME:'Missing Report Name',
							REPORT_NAME_EXISTS:'Report name already exists, try again...',
							WANT_TO_CHANGE_CONTACT_ADDR:'Do you want to change the addresses of the Contacts related to this Account?',
							SURE_TO_DELETE:'Are you sure you want to delete ?',
							NO_PRODUCT_SELECTED:'No product is selected. Select at least one Product',
							VALID_FINAL_PERCENT:'Enter valid Final Discount Percentage',
							VALID_FINAL_AMOUNT:'Enter valid Final Discount Amount',
							VALID_SHIPPING_CHARGE:'Enter a valid Shipping & Handling charge',
							VALID_ADJUSTMENT:'Enter a valid Adjustment',
							WANT_TO_CONTINUE:'Do you want to Continue?',
							ENTER_VALID_TAX:'Please enter Valid TAX value',
							VALID_TAX_NAME:'Enter valid Tax Name',
							CORRECT_TAX_VALUE:'Enter Correct Tax Value',
							ENTER_POSITIVE_VALUE:'Please enter positive value',
							LABEL_SHOULDNOT_EMPTY:'The tax label name should not be empty',
							NOT_VALID_ENTRY:'is not a valid entry. Please enter correct value',
							VALID_DISCOUNT_PERCENT:'Enter a valid Discount percentage',
							VALID_DISCOUNT_AMOUNT:'Enter a valid Discount Amount',
							LBL_PRODUCT:'Product',
							LBL_QTY:'Qty',
							LBL_LISTPRICE:'List Price',
							LBL_PRODUCT_NAME:'Product Name',
							SELECT_TEMPLATE_TO_MERGE:'Please select a template to merge',
							SELECTED_MORE_THAN_ONCE:'You have selected the following product(s) more than once.',
							YES:'yes',
							NO:'no',
							MAIL:'mail',
							EQUALS:'equals',
							NOT_EQUALS_TO:'not equal to',
							STARTS_WITH:'starts with',
							CONTAINS:'contains',	
							DOES_NOT_CONTAINS:'does not contains',
							LESS_THAN:'less than',
							GREATER_THAN:'greater than',
							LESS_OR_EQUALS:'less or equal',
							GREATER_OR_EQUALS:'greater or equal',
							NO_SPECIAL_CHARS:'Special Characters are not allowed in Invoice String',
							PLS_SELECT_VALID_FILE:'Please select a file with the following extension:\n',
							NO_SPECIAL:'Special Characters are not allowed',
							IN_PROFILENAME:' in Profile Name',
							IN_GROUPNAME:' in Group Name',
							IN_ROLENAME:' in Role Name',
							VALID_TAX_PERCENT:'Enter a valid Tax percentage',
							VALID_SH_TAX:'Enter valid Taxes for shipping and handling ',
							ROLE_DRAG_ERR_MSG:'You cannot move a Parent Node under a Child Node',
							LBL_DEL:'del',
							VALID_DATA :' Enter Valid Data ,Please try again... ',
							STDFILTER : 'Standard Filters',
							STARTDATE : 'Start Date',
							ENDDATE : 'End Date',
							START_DATE_TIME : 'Start Date & Time',
							START_TIME : 'Start Time',
							DATE_SHOULDNOT_PAST :'Current date & time for Activities with status as Planned',
							TIME_SHOULDNOT_PAST :'Current Time for Activities with status as Planned',
							LBL_AND : 'And',
							LBL_ENTER_VALID_PORT: 'Please enter valid port number',
							IN_USERNAME :' in Username ',
							LBL_ENTER_VALID_NO: 'Please enter valid number',
							LBL_PROVIDE_YES_NO: ' Invalid value.\n Please Provide Yes or No',
							LBL_SELECT_CRITERIA: ' Invalid criteria.\n Please select criteria',
							OPPORTUNITYNAME_CANNOT_BE_EMPTY:'Potential Name field cannot be empty',
							OVERWRITE_EXISTING_ACCOUNT1:'Do you want to Overwrite the existing address with this selected account(',
							NAME_DESC:' for Folder Name & Description',
							ENDS_WITH:'ends with',
							SHARED_EVENT_DEL_MSG:'The User does not have permission to Edit/Delete Shared Event.',
							LBL_WRONG_IMAGE_TYPE: 'Allowed file types for Contacts - jpeg, png, jpg, pjpeg, x-png or gif',
							SELECT_MAIL_MOVE: 'Please select a mail and then move..',
							LBL_NOTSEARCH_WITHSEARCH_ALL:'You haven\'t used the search. All the records will be Exported from ',
							LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE:'You haven\'t searched any thing. But you selected with search & current page options. So the records in the current page will be Exported from ',
							LBL_NO_DATA_SELECTED:'There is no record selected. Select at least one record to Export',
							LBL_SEARCH_WITHOUTSEARCH_ALL:'You have used search option but you have not selected without search & all options.\nYou can click [ok] to export all data or You can click [cancel] and try again with other export criteria',
							STOCK_IS_NOT_ENOUGH : 'Stock is not enough',
							INVALID_QTY : 'Invalid Qty',
							LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE:'You have used search option but you have not selected without search & currentpage options.\nYou can click [ok] to export current page data or You can click [cancel] and try again with some other export criteria.',
							CONFIRM_APPROVE:'Sure to Approve?',
							ALREADY_APPROVED:'Already Approved!',
							APPROVE_FAILED:'Fail to approve',
							APPROVED:'Finish approving',
							ACCOUNT_CANNOT_EMPTY:'Account Cannot be Empty',
							VENDOR_CANNOT_EMPTY:'Vendor Cannot be Empty',
							LABEL:'Label',
							LENGTH:'Length',
							IMAGE_DELETED:'Image deleted',
							ERROR_WHILE_DELING:'Error while deling',
							REJECT_DESC:'Reject reason',
							INPUT_REJECT_DESC:'Pls input reject reason',
							LOG_Enabled:'Enable system log',
							LOG_Disabled:'Disable system log',
							EXPORT_Disabled:'Export disabled!',
							SELECT_MERGED_FILE:'Select merged file',
							MORE_THAN_MAXISIEZED_FILE:'More than maxisized file!',
							UPLOAD_ERROR:'Upload error,Pls try again!',
							INVALID_EMAIL:"'Invalid Email",
							PASSWORD_MISMATCH:'Password mismatch',
							INPUT_TAG:"Pls input tag",
							INVALID_LISTPRICE:"Invalid listprice",
							LISTPRICE_ISNOT_NULL:"List Price cannot be empty!",
							TEMPLATE_ISNOT_NULL:"Template cannot be empty!",
							FOLDER_ISNOT_NULL:"Folder cannot be empty!",
							TEMPLATE_TITLE_ISNOT_NULL:"Template Title cannot be empty!",
							INPUT_ROLE:'Pls input role',
							ROLE_NAME:'Pls input role name',
							CURRENCY_NAME:"Currency Name",
							CURRENCY_CODE:"Currency Code",
							CURRENCY_SYMBOL:"Currency Symbol",
							CURRENCY_RATE:"Currency Rate",
							CURRENCY_STATUS:"Currency Status",
							INPUT_VALID_CURRENCY:"Pls input valid currency",
							SELECT_REQUIRED_FIELD:"Select required field",
							FIELD_REPEATED:'Field repeated',
							SELECT_ROLE:'Pls select role',
							INPUT_VALID_TAX:"Pls input valid tax",
							IMPORTED_FILE_ISNOT_NULL:'Imported file cannot be empty!',
							MAPPING_LIST_DELETED:"Mapping list has been deleted.",
							SELECT_PARENT_OR_SUBROLE:"Pls select parent role and subrole",
							ACCOUNT_PRIVATE_AND_POTENTIAL_SO_PO_PRIVATE:"Potential,Trouble Tickets,Quote,SalesOrder and Invoice must be private when aAccount is private.",
							ROLE_UPDATED:"Role info has been updated",
							SELECT_ONE_REPORT:'Select one report',
							ROLE_RELATED_TO_ONE_PROFILE:'Role must be related to a profile!',
							SELECT_NEW_CATALOG:'Pls select new catalog',
							SELECT_PARENT_OR_SUBCATALOG:"Pls select parent catalog or subordinate catalog",
							Set_Discount_for:"Set discount for",
							Set_Tax_for:"Set tax for ",
							Set_SH_Tax_for:"Set sh_tax for ",
							Set_Group_Tax_for:"Set group tax for ",
							ANNOUNCEMENT_IS_NULL:"Announcement cannot be empty!",
							STARTDATE_IS_NULL:"Startdate cannot be empty!",
							PARENTTAB_KEY_IS_NULL:"Parent tab cannot be empty",
							INPUT_VALID_CHARACTER:"Pls input valid character",
							PARENTTAB_LABEL_IS_NULL:"Parent tab label cannot be empty!",
							BLOCK_LABEL_IS_NULL:"Block label cannot be empty!",
							DISPLAY_ORDER_IS_NULL:"Display order  cannot be empty!",
							MODULES_FOLDER_NOT_WRITABLE:"Modules folder cannot be writable!",
							MODULES_EXISTED:"Module Existed",
							TAB_KEY_IS_NULL:"Tab Key cannot be empty!",
							TAB_LABEL_IS_NULL:"Tab label cannot be empty!",
							SERVER_IS_NULL:"Server cannot be empty!",
							SERVER_PORT_IS_NULL:"Server port cannot be empty",
							DATABASE_USERNAME_IS_NULL:"Database username cannot be empty",
							DATABASE_IS_NULL:"Database cannot be empty!",
							DATABASE_PREFIX_IS_NULL:"Database prefix cannot be empty!",
							SYNC_SUCCESS:"Sync successfully",
							FAILED_TO_SYNC:"Failed to Sync",
							SURE_TO_EXPORT:'Sure to export?',
							SURE_TO_UNINSTALL:'Sure to uninstall?',
							SURE_TO_INSTALL:'Sure to install?',
							SURE_TO_MOVE_REPORT:"Sure to move report?",
							SURE_TO_MOVE_WORKFLOW:"Sure to move workflow?",
							NONE:"None",
		                    CUSTOM_VIEW_NAME:"Custom view name",
		                    SUBJECT:"Subject",
		                    FINISH:" Finish ",
	                        CONFIG_SMTP_FIRST:"Pls config smtp info first",
	                        MAILLISTNAME_IS_NULL:"Maillist name cannot be empty!",
	                        MAILLIST_SUBJECT_IS_NULL:"Maillist subject cannot be empty!",
							MAILLIST_SENT:"Mail Sent",
		                    CATALOG_NAME:"Catalog Name",
	                        COLLECTION_TOTAL_EQUAL_SALESORDER_TOTAL:"Total of collections is equal to total of salesorder!",
	                        COLLECTION_IS_NULL:"Collection cannot be empty or 0!",
	                        COLLECTION_TIMES_IS_NULL:"Collection times cannot be empty or 0!",
	                        COLLECTION_DATE_IS_NULL:"Collection date cannot be empty!",
	                        COLLECTION_DATE:"Collection date",
	                        COLLECTION_TIMES:"Collection times",
	                        COLLECTION:"Collection",
	                        COLLECTION_TOTAL_NOT_EQUAL_SALESORDER_TOTAL:"Total of collections is not equal to total of salesorder!",
		                    CHARGE_TOTAL_EQUAL_PO_TOTAL:"Total of charges is equal to total of purchaseorder!",
							CHARGE_IS_NULL:"Charge cannot be empty or 0!",
	                        CHARGE_TIMES_IS_NULL:"Charge times cannot be empty or 0!",
	                        CHARGE_DATE_IS_NULL:"Charge date cannot be empty!",
	                        CHARGE_DATE:"Charge date",
	                        CHARGE_TIMES:"Charge times",
	                        CHARGE:"Charge",
	                        CHARGE_TOTAL_NOT_EQUAL_PO_TOTAL:"Total of charges is not equal to total of purchaseorder!",
		                    CLEAR_COMMENT:"Clear Comment",
		                    DELIVERED:"Deliverd",
		                    APPROVE_BEFORE_DELIVER:"Approve before delivered",
		                    PRODUCTCODE_IS_NULL:"Product code cannot be empty!",
		                    PRODUCTNAME_IS_NULL:"Product name cannot be empty!",
		                    PHONE_OR_EMAIL_IS_NULL:"Phone & Email cannot be empty!",
		                    ACCOUNT_NAME_EXISTS:'Account name exists!',
		                    VENDOR_NAME_EXISTS:'Vendor name exists!',
		                    PRODUCTCODE_EXISTS:'Product exists!',
		                    RECIPIENT_IS_NULL:'Recipient cannot be empty!',
	                        MESSAGE_IS_NULL:'Message cannot be empty!',
	                        USER_NOT_EXISTS:'User does not exist!',
		                    PRODUCT_SELECTED:'Product has been selected!',
		                    SURE_TO_ANTI_APPROVE:'Are you sure to anti approve the record?',
		                    SURE_TO_CANCEL_APPROVE:'Are you sure to cancel the record?',
		                    SELECT_NEW_FAQCATEGORY:'Pls select new category',
		                    MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE: 'Unit price of all the Currencies will be revised based on the selected Currency. Are you sure?',
							CONTACT_NAME_EXISTS:'Contact name exists!',
		                    COLLECTION_YISHOU:"已收",
							COLLECTION_WEISHOU:"未收",
							COLLECTION_BUFENYISHOU:"部分已收",
	                        COLLECTION_ACTUALAMOUNT:"实收金额",
                            COLLECTION_PLANAMOUNT:"应收金额",
		                    RELATEDMODULE_REPEATED:'Related Module Field repeated!',
		                    RELATEDMODULE1_ISNULL:'其它模块字段1不能为空',
	                        RELATEDMODULE2_ISNULL:'其它模块字段2不能为空'
         };
//calendar string
var monthArray = ['January','February','March','April','May','June','July','August','September','October','November','December'];
var monthArrayShort = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
var dayArray = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
var weekString = 'Week';
var todayString = '';
