var alert_arr = {			DELETE:'确认删除选择 ',
							RECORDS:' 记录?',
							SELECT:'请至少选择一条记录',
							DELETE_ACCOUNT:'Deleting this account(s) will remove its related Potentials & Quotes. Are you sure you want to delete the selected ',
							DELETE_VENDOR:'Deleting this vendor(s) will remove its related Purchase Orders. Are you sure you want to delete the selected ',
							SELECT_MAILID:'请选择一个Email',
							OVERWRITE_EXISTING_ACCOUNT2:') address details?',
							MISSING_FIELDS:'必填字段不能为空:',
							NOT_ALLOWED_TO_EDIT:'禁止编辑这个字段',
							COLUMNS_CANNOT_BE_EMPTY:'选择字段不能为空',
							CANNOT_BE_EMPTY:' 不能为空',
							CANNOT_BE_NONE:' 不能为空',
							ENTER_VALID:'请输入有效的 ',
							SHOULDBE_LESS:' 应该小于 ',
							SHOULDBE_LESS_EQUAL:' 应该小于等于 ',
							SHOULDBE_EQUAL:' 应该等于 ',
							SHOULDBE_GREATER:' 应该大于 ',
							SHOULDBE_GREATER_EQUAL:' 应该大于等于 ',
							INVALID:'无效的 ',
							EXCEEDS_MAX:' 超过最大限制 ',
							OUT_OF_RANGE:' 越界',
							SHOULDNOTBE_EQUAL:' 应该等于 ',
							PORTAL_PROVIDE_EMAILID:'Portal用户应该提供有效的Email',
							ADD_CONFIRMATION:'Are you sure you want to add the selected ',
							ACCOUNTNAME_CANNOT_EMPTY:'客户名称不能为空',
							CANT_SELECT_CONTACTS:"You can\'t select related contacts from Lead",
							LBL_THIS:'This ',
							DOESNOT_HAVE_MAILIDS:" doesn\'t have any mail ids",
							ARE_YOU_SURE:'您确认要执行吗?',
							DOESNOT_HAVE_AN_MAILID:"Email为空！",
							MISSING_REQUIRED_FIELDS:'必填字段不能为空: ',
							READONLY:"只读",
							SELECT_ATLEAST_ONE_USER:'至少选择一个用户',
							DISABLE_SHARING_CONFIRMATION:'Are you sure you want to disable sharing for selected ',
							USERS:' user(s) ?',
							ENDTIME_GREATER_THAN_STARTTIME:'结束时间应该大于开始时间 ',
							FOLLOWUPTIME_GREATER_THAN_STARTTIME:'Followup Time should be greater than End Time ',
							MISSING_EVENT_NAME:'Missing Event Name',
							EVENT_TYPE_NOT_SELECTED:'Event Type is not selected',
							CLOSEDATE_CANNOT_BE_EMPTY:'Close Date field cannot be empty',
							SITEURL_CANNOT_BE_EMPTY:'Site Url cannot be empty',
							SITENAME_CANNOT_BE_EMPTY:'Site Name cannot be empty',
							LISTPRICE_CANNOT_BE_EMPTY:'价格不能为空',
							INVALID_LIST_PRICE:'无效的价格',
							PROBLEM_ACCESSSING_URL:'Problem accessing url: ',
							CODE:' Code: ',
							WISH_TO_QUALIFY_MAIL_AS_CONTACT:'Are you sure you wish to Qualify this Mail as Contact?',
							SELECT_ATLEAST_ONEMSG_TO_DEL:'Please select at least one message to delete',
							ERROR:'错误',
							FIELD_TYPE_NOT_SELECTED:'没有选择字段类型',		                        
							SPECIAL_CHARACTERS_NOT_ALLOWED:'标签禁止包含特殊字符',
							PICKLIST_CANNOT_BE_EMPTY:'下拉框列表值不能为空',
							DUPLICATE_VALUES_FOUND:'下拉框列表值重复',
							DUPLICATE_MAPPING_ACCOUNTS:'重复映射!',
							DUPLICATE_MAPPING_CONTACTS:'重复映射!',
							DUPLICATE_MAPPING_POTENTIAL:'重复映射!',
							ERROR_WHILE_EDITING:'编辑错误',
							CURRENCY_CHANGE_INFO:'Currency Changes has been made Successfully',
							CURRENCY_CONVERSION_INFO:'Are you using Dollar $ as Currency? \n Click OK to remain as $, Cancel to change the currency conversion rate.',
							THE_EMAILID: "The email id \'",
							EMAIL_FIELD_INVALID:"\' in the email field is invalid",
							MISSING_REPORT_NAME:'报表名称不能为空',
							REPORT_NAME_EXISTS:'报表名称已存在，请重试...',
							WANT_TO_CHANGE_CONTACT_ADDR:'Do you want to change the addresses of the Contacts related to this Account?',
							SURE_TO_DELETE:'确认删除？',
							NO_PRODUCT_SELECTED:'请至少选择一个产品',
							VALID_FINAL_PERCENT:'输入有效的折扣比例',
							VALID_FINAL_AMOUNT:'输入有效的折扣数量',
							VALID_SHIPPING_CHARGE:'输入有效的税率',
							VALID_ADJUSTMENT:'输入有效的调整',
							WANT_TO_CONTINUE:'继续？',
							ENTER_VALID_TAX:'Please enter Valid TAX value',
							VALID_TAX_NAME:'Enter valid Tax Name',
							CORRECT_TAX_VALUE:'Enter Correct Tax Value',
							ENTER_POSITIVE_VALUE:'Please enter positive value',
							LABEL_SHOULDNOT_EMPTY:'The tax label name should not be empty',
							NOT_VALID_ENTRY:'is not a valid entry. Please enter correct value',
							VALID_DISCOUNT_PERCENT:'输入有效的折扣比例',
							VALID_DISCOUNT_AMOUNT:'输入有效的折扣数量',
							LBL_PRODUCT:'产品',
							LBL_QTY:'数量',
							LBL_LISTPRICE:'价格',
							LBL_PRODUCT_NAME:'产品名称',
							SELECT_TEMPLATE_TO_MERGE:'Please select a template to merge',
							SELECTED_MORE_THAN_ONCE:'以下产品选择多次。',
							YES:'是',
							NO:'不',
							MAIL:'mail',
							EQUALS:'等于',
							NOT_EQUALS_TO:'不等于',
							STARTS_WITH:'开始为',
							CONTAINS:'包含',	
							DOES_NOT_CONTAINS:'不包含',
							LESS_THAN:'小于',
							GREATER_THAN:'大于',
							LESS_OR_EQUALS:'小于等于',
							GREATER_OR_EQUALS:'大于等于',
							NO_SPECIAL_CHARS:'Special Characters are not allowed in Invoice String',
							PLS_SELECT_VALID_FILE:'Please select a file with the following extension:\n',
							NO_SPECIAL:'Special Characters are not allowed',
							IN_PROFILENAME:' in Profile Name',
							IN_GROUPNAME:' in Group Name',
							IN_ROLENAME:' in Role Name',
							VALID_TAX_PERCENT:'Enter a valid Tax percentage',
							VALID_SH_TAX:'Enter valid Taxes for shipping and handling ',
							ROLE_DRAG_ERR_MSG:'You cannot move a Parent Node under a Child Node',
							LBL_DEL:'删除',
							VALID_DATA :' 请输入有效的数据，请重试... ',
							STDFILTER : '标准过滤器',
							STARTDATE : '开始日期',
							ENDDATE : '结束日期',
							START_DATE_TIME : '开始日期和时间',
							START_TIME : '开始时间',
							DATE_SHOULDNOT_PAST :'Current date & time for Activities with status as Planned',
							TIME_SHOULDNOT_PAST :'Current Time for Activities with status as Planned',
							LBL_AND : 'And',
							LBL_ENTER_VALID_PORT: '请输入有效的端口',
							IN_USERNAME :' in Username ',
							LBL_ENTER_VALID_NO: '请输入有效的数字',
							LBL_PROVIDE_YES_NO: ' 无效的值。\n 请输入是或不',
							LBL_SELECT_CRITERIA: ' 无效的条件。\n 请选择条件',
							OPPORTUNITYNAME_CANNOT_BE_EMPTY:'销售机会名称不能为空',
							OVERWRITE_EXISTING_ACCOUNT1:'Do you want to Overwrite the existing address with this selected account(',
							NAME_DESC:' for Folder Name & Description',
							ENDS_WITH:'结束为',
							SHARED_EVENT_DEL_MSG:'The User does not have permission to Edit/Delete Shared Event.',
							LBL_WRONG_IMAGE_TYPE: '允许的文件类型：jpeg, png, jpg, pjpeg, x-png 和 gif',
							SELECT_MAIL_MOVE: 'Please select a mail and then move..',								
							LBL_NOTSEARCH_WITHSEARCH_ALL:'You haven\'t used the search. All the records will be Exported from ',
							LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE:'You haven\'t searched any thing. But you selected with search & current page options. So the records in the current page will be Exported from ',
							LBL_NO_DATA_SELECTED:'There is no record selected. Select at least one record to Export',
							LBL_SEARCH_WITHOUTSEARCH_ALL:'You have used search option but you have not selected without search & all options.\nYou can click [ok] to export all data or You can click [cancel] and try again with other export criteria',
							STOCK_IS_NOT_ENOUGH : 'Stock is not enough',
							INVALID_QTY : '无效的数量',
							LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE:'You have used search option but you have not selected without search & currentpage options.\nYou can click [ok] to export current page data or You can click [cancel] and try again with some other export criteria.',
							CONFIRM_APPROVE:'确认审批通过？',
							ALREADY_APPROVED:'已经审批过！',
							APPROVE_FAILED:'审批失败',
							APPROVED:'完成审批操作',
							ACCOUNT_CANNOT_EMPTY:'客户不能为空',
							VENDOR_CANNOT_EMPTY:'供应商不能为空',
							LABEL:'标签',
							LENGTH:'长度',
							IMAGE_DELETED:'图片已删除',
							ERROR_WHILE_DELING:'删除错误',
							REJECT_DESC:'审批备注',
							INPUT_REJECT_DESC:'请输入审批备注',
							LOG_Enabled:'激活系统日志',
							LOG_Disabled:'禁止系统日志',
							EXPORT_Disabled:'您不允许执行导出操作！',
							SELECT_MERGED_FILE:'请指定合并文件',
							MORE_THAN_MAXISIEZED_FILE:'上传文件超过最大限制！',
							UPLOAD_ERROR:'上传文件出错，请重新上传！',
							INVALID_EMAIL:"'是无效的Email，请重新输入",
							PASSWORD_MISMATCH:'密码不匹配',
							INPUT_TAG:"请输入标签",
							INVALID_LISTPRICE:"无效的价格",
							LISTPRICE_ISNOT_NULL:"价格不能为空",
							TEMPLATE_ISNOT_NULL:"模板名称不能为空！",
							FOLDER_ISNOT_NULL:"文件夹名称不能为空！",
							TEMPLATE_TITLE_ISNOT_NULL:"模板主题不能为空！",
							INPUT_ROLE:'请输入角色名称',
							ROLE_NAME:'请输入角色名称',
							CURRENCY_NAME:"货币名称",
							CURRENCY_CODE:"货币编码",
							CURRENCY_SYMBOL:"货币标志",
							CURRENCY_RATE:"汇率",
							CURRENCY_STATUS:"货币状态",
							INPUT_VALID_CURRENCY:"请输入有效汇率",
							SELECT_REQUIRED_FIELD:"至少选择一个必填字段",
							FIELD_REPEATED:'栏目不能重复',
							SELECT_ROLE:'请指定角色',
							INPUT_VALID_TAX:"请输入有效的税值",
							IMPORTED_FILE_ISNOT_NULL:'导入文件不能为空！',
							MAPPING_LIST_DELETED:"这个字段映射表已经被删除。您不能再使用",
							SELECT_PARENT_OR_SUBROLE:"请指定上级或下级角色",
							ACCOUNT_PRIVATE_AND_POTENTIAL_SO_PO_PRIVATE:"当客户设为私有时，销售机会，故障单，报价，合同订单和发票都必须设为私有。",
							ROLE_UPDATED:"角色信息已更新",
							SELECT_ONE_REPORT:'请至少选择一个报表',
							ROLE_RELATED_TO_ONE_PROFILE:'角色至少与一个用户组关联！',
							SELECT_NEW_CATALOG:'请指定新的产品分类',
							SELECT_PARENT_OR_SUBCATALOG:"请指定上级或下级分类",
							Set_Discount_for:"设置折扣",
							Set_Tax_for:"设置税额",
							Set_SH_Tax_for:"设置运费和物流附加费的税",
							Set_Group_Tax_for:"设置公司所交的税",
							ANNOUNCEMENT_IS_NULL:"通告信息不能为空！",
							STARTDATE_IS_NULL:"开始日期不能为空！",
							PARENTTAB_KEY_IS_NULL:"主模块英文名称不能为空！",
							INPUT_VALID_CHARACTER:"请输入有效的英文字母",
							PARENTTAB_LABEL_IS_NULL:"主模块中文名称不能为空！",
							BLOCK_LABEL_IS_NULL:"显示区域标题不能为空！",
							DISPLAY_ORDER_IS_NULL:"显示顺序不能为空！",
							MODULES_FOLDER_NOT_WRITABLE:"modules目录不可写！",
							MODULES_EXISTED:"模块已存在！",
							TAB_KEY_IS_NULL:"英文名称不能为空！",
							TAB_LABEL_IS_NULL:"显示名称不能为空！",
							SERVER_IS_NULL:"数据库服务器不能为空",
							SERVER_PORT_IS_NULL:"数据库服务器端口不能为空",
							DATABASE_USERNAME_IS_NULL:"数据库用户名不能为空",
							DATABASE_IS_NULL:"数据库名字不能为空",
							DATABASE_PREFIX_IS_NULL:"数据库前缀不能为空",
							SYNC_SUCCESS:"同步完成",
							FAILED_TO_SYNC:"同步失败",
							SURE_TO_EXPORT:'确认导出？',
							SURE_TO_UNINSTALL:'确认卸载？',
							SURE_TO_INSTALL:'确认安装？',
							SURE_TO_MOVE_REPORT:"确认移动报表？",
							SURE_TO_MOVE_WORKFLOW:"确认移动工作流？",
	                        NONE:"无",
	                        CUSTOM_VIEW_NAME:"视图名称",
	                        SUBJECT:"主题",
	                        FINISH:" 完成 ",
	                        CONFIG_SMTP_FIRST:"请配置您的邮件服务器",
	                        MAILLISTNAME_IS_NULL:"方案名称必填",
	                        MAILLIST_SUBJECT_IS_NULL:"邮件主题必填",
							MAILLIST_SENT:"发送完成",
	                        CATALOG_NAME:"产品分类名称",
	                        COLLECTION_TOTAL_EQUAL_SALESORDER_TOTAL:"应收款总额已经等于总金额！",
	                        COLLECTION_IS_NULL:"应收款不能为空或0！",
	                        COLLECTION_TIMES_IS_NULL:"期次不能为空或0！",
	                        COLLECTION_DATE_IS_NULL:"应收日期不能为空！",
	                        COLLECTION_DATE:"应收日期",
	                        COLLECTION_TIMES:"期次",
	                        COLLECTION:"应收款",
	                        COLLECTION_TOTAL_NOT_EQUAL_SALESORDER_TOTAL:"应收款和总金额不符！",
	                        CHARGE_TOTAL_EQUAL_PO_TOTAL:"应付款总额已经等于总金额！",
							CHARGE_IS_NULL:"应付款不能为空或0！",
	                        CHARGE_TIMES_IS_NULL:"期次不能为空或0！",
	                        CHARGE_DATE_IS_NULL:"应付日期不能为空！",
	                        CHARGE_DATE:"应付日期",
	                        CHARGE_TIMES:"期次",
	                        CHARGE:"应付款",
	                        CHARGE_TOTAL_NOT_EQUAL_PO_TOTAL:"应付款和总金额不符！",
	                        CLEAR_COMMENT:"清除备注",
	                        DELIVERED:"已出库",
	                        APPROVE_BEFORE_DELIVER:"审批通过后才能出库！",
	                        PRODUCTCODE_IS_NULL:"产品编码不能为空",
							PRODUCTNAME_IS_NULL:"产品名称不能为空",
                            PHONE_OR_EMAIL_IS_NULL:"联系方式不能为空",
	                        ACCOUNT_NAME_EXISTS:'客户名称已存在，请重试...',
	                        VENDOR_NAME_EXISTS:'供应商名称已存在，请重试...',
	                        PRODUCTCODE_EXISTS:'产品已存在，请重试...',
							MAX_THREE:'最多3个',
							SAME_GROUPS:'所选记录要在同一组',
							ATLEAST_TWO:'至少2个',
							PRODUCTCODE_EXISTS:'产品已存在，请重试...',
	                        RECIPIENT_IS_NULL:'接收人不能为空',
	                        MESSAGE_IS_NULL:'内容不能为空',
	                        USER_NOT_EXISTS:'接收人不存在',
	                        PRODUCT_SELECTED:'产品已经选择',
	                        SURE_TO_ANTI_APPROVE:'确认反审批？',
	                        SURE_TO_CANCEL_APPROVE:'确认撤单？撤单将删除合同订单相关的应收款、发货单和出库单。出库单如果已出库，撤单后库存将恢复到出库前的数量。',
	                        SELECT_NEW_FAQCATEGORY:'请选择新的分类',
	                        MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE: '确认根据所选币种的汇率计算产品价格？',
	                        CONTACT_NAME_EXISTS:'联系人已存在，请重试...',
	                        COLLECTION_YISHOU:"已收",
							COLLECTION_WEISHOU:"未收",
							COLLECTION_BUFENYISHOU:"部分已收",
	                        COLLECTION_ACTUALAMOUNT:"实收金额",
                            COLLECTION_PLANAMOUNT:"应收金额",
	                        RELATEDMODULE_REPEATED:'关联模块字段不能重复',
	                        RELATEDMODULE1_ISNULL:'其它模块字段1不能为空',
	                        RELATEDMODULE2_ISNULL:'其它模块字段2不能为空'
                       };

//calendar string
var monthArray = ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'];
var monthArrayShort = ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'];
var dayArray = ['一','二','三','四','五','六','日'];
var weekString = '周';
var todayString = '';
